feat: add claim kint guide
interlay/interlay.github.io pull request #142
Opened 2021-12-14 07:44 UTC by nud3l

2021-12-15 12:18 UTC, alexeiZamyatin commented
Added 2 comments. 

Missing: a section on how people can check their KINT balance.

2021-12-16 04:14 UTC, nud3l commented
> Added 2 comments.
> 
> Missing: a section on how people can check their KINT balance.

I think you did not submit your review. Can you check if you pressed the button since I don't see any comments? Thanks!

2021-12-16 09:22 UTC, alexeiZamyatin requested changes

2021-12-16 09:22 UTC, alexeiZamyatin commented on docs/kintsugi/crowdloans.md
> +Click the checkbox accept the terms and conditions.
```suggestion
You MUST read and accept the terms and conditions to qualify for the airdrop.
```

2021-12-16 09:22 UTC, alexeiZamyatin commented on docs/kintsugi/crowdloans.md
> +?> Signing the T&Cs is free of charge, i.e., there are no transaction fees for signing the T&Cs.
```suggestion
?> There are **no** transaction fees for signing the T&Cs.
```

2021-12-16 10:58 UTC, alexeiZamyatin approved these changes

2021-12-16 10:58 UTC, merged