feat: add vault checklist and fix kintsugi instructions
interlay/interlay.github.io pull request #186
Opened 2022-03-17 11:07 UTC by gregdhill

Signed-off-by: Gregory Hill <gregorydhill@outlook.com>

2022-03-17 15:54 UTC, alexbleau commented on docs/vault/installation.md
> +- [x] Transfer collateral from the relay chain
I would add here a link to how to transfer collateral from Kusama to Kintsugi. See this page updated today by Tom - https://docs.interlay.io/#/guides/transfers?id=transfer-guide

2022-03-17 15:55 UTC, alexbleau commented on docs/vault/installation.md
> +- [x] Transfer collateral from the relay chain
nevermind. saw where you linked to it :)

2022-03-18 10:24 UTC, nud3l requested changes

2022-03-18 10:24 UTC, nud3l commented on docs/vault/faq.md
> +Yes! Vaults earn fees in interBTC and KINT/INTR.
```suggestion
Yes! Vaults earn fees in kBTC/interBTC and KINT/INTR.
```

2022-03-18 10:24 UTC, nud3l commented on docs/vault/faq.md
> +Vaults must lock up collateral worth ``150%`` of the locked BTC value.
Insert link to the collateral thresholds

```suggestion
Vaults must lock up collateral depending on the collateral and network based on the collateral thresholds: 
```

2022-03-18 10:24 UTC, nud3l commented on docs/vault/faq.md
>  The Vault's collateral, up to ``150%`` of the stolen BTC value at the current exchange rate, is slashed and the interBTC bridge initiates a [**Burn Event**](/overview?id=burn-event-restoring-a-11-phy
This also needs to be updated with the link to the thresholds since it depends on the collateral.

2022-03-18 10:24 UTC, nud3l commented on docs/vault/installation.md
> +- [x] Generate Sr25519 key(s) for the parachain
Please link to the right guides for the checklist so that vaults know where to find it in the docs.

2022-03-18 10:24 UTC, nud3l commented on docs/vault/installation.md
Would update like:

```md
!> Ensure that you have a backup of the substrate key in a safe place.

Create a `keyfile.json` file that contains the mnemonic of the substrate account you want to use for the Vault, e.g.:
```

2022-03-18 10:24 UTC, nud3l commented on docs/vault/installation.md
> +
Add:

```
Please also check the minimum collateral requirements for Vaults: INSERT LINK
```

Do we have that documented already somewhere?

2022-03-18 10:24 UTC, nud3l commented on docs/vault/installation.md
Add:

```md
- Have at least 1 KINT/INTR to pay for initial transaction fees.
- Have a minimum amount of collateral assets, see INSERT LINK TO REQUIREMENTS
```

2022-03-18 11:31 UTC, nud3l approved these changes

2022-03-18 11:31 UTC, merged